# Generated by Django 6.1.1 on 2026-09-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='specialist_id',
            new_name='specialist',
        ),
    ]
