# Generated by Django 6.1.1 on 2026-09-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='specialist_service',
            new_name='SpecialistService',
        ),
    ]
